characters = {"BRETT",
              "BUDDY",
              "BUTCH",
              "CAPT. KOONS",
              "ED SULLIVAN",
              "ENGLISH DAVE",
              "ESMARELDA",
              "FABIENNE",
              "FOURTH MAN",
              "GAWKER #1",
              "GAWKER #2",
              "HONEY BUNNY",
              "JIMMIE",
              "JODY",
              "JULES",
              "KLONDIKE",
              "LANCE",
              "LOOKY-LOO WOMAN",
              "MANAGER",
              "MARSELLUS",
              "MARVIN",
              "MAYNARD",
              "MIA",
              "MOTHER",
              "PATRON",
              "PEDESTRIAN",
              "PREACHER (EMIL SIMKUS)",
              "PUMPKIN",
              "RAQUEL",
              "ROGER",
              "SPORTSCASTER #1",
              "SPORTSCASTER #2",
              "THE GIMP",
              "THE WOLF",
              "TRUDI",
              "VINCENT",
              "WAITRESS",
              "WINSTON",
              "WOMAN'S VOICE",
              "YOLANDA",
              "YOUNG MAN",
              "YOUNG WOMAN",
              "ZED"}